### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by rykm48** [gtalusan/eufy-device-id-js#2]
when i run hbadmin@homebridge-ubuntu:~/eufy-device-id-js$ node index.js "myemail@gmail.com" "mypassword" i get the following error message

Error: TypeError: Cannot read properties of undefined (reading 'id')
    at EufyHomeSession.login (/home/hbadmin/eufy-device-id-js/lib/clients.js:77:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EufyHomeSession._request (/home/hbadmin/eufy-device-id-js/lib/clients.js:84:13)
    at async /home/hbadmin/eufy-device-id-js/index.js:14:22

**Comment by gtalusan** [comment]
You can modify the code to figure out what the response is from the API

https://github.com/gtalusan/eufy-device-id-js/blob/d7e95bc6a031f26f260058f53351c9568035574b/lib/clients.js#L76

Put in a console.log and maybe there’s an error.

**Comment by rykm48** [comment]
where do i put im console.log?  im not sure what to type where

**Comment by rykm48** [comment]
the exact steps i did to get this far is in ubuntu terminal
git clone https://github.com/gtalusan/eufy-device-id-js
cd eufy-device-id-js
npm install
and then ran node index.js "myemail@gmail.com" "password123"

**Comment by gtalusan** [comment]
Not sure if Copilot is doing something wrong or what... but look for this code:

```
    async login() {
        const response = await this.session.post(this.url('user/email/login'), {
            client_Secret: EUFY_CLIENT_SECRET,
            client_id: EUFY_CLIENT_ID,
            email: this.email,
            password: this.password
        });
        
        const data = response.data;
        this.session.defaults.headers['uid'] = data.user_info.id;
        this.session.defaults.headers['token'] = data.access_token;
        this.base_url = data.user_info.request_host;
    }
```
This is in the file clients.js, in the class EufyHomeSession (which Copilot claims to not exist).  Find:

```
const data = response.data;
```
and change to:
```
const data = response.data
console.log(data);
```
and re-run it.

**Comment by rykm48** [comment]
found it, thank you!!  log told me my login was incorrect however i know the password is correct, upon looking in the eufy app i forgot to add the +eufy to my email address in my password manager

**Comment by gtalusan** [comment]
Great, you're welcome and happy to help!

**Comment by imperatorviken** [comment]
Hi @rykm48 what do you mean by adding +eufy to your email address ?
Sorry to bother i have the same issue :/

**Comment by rykm48** [comment]
> Hi [@rykm48](https://github.com/rykm48) what do you mean by adding +eufy to your email address ? Sorry to bother i have the same issue :/

When I registered my email with eufy I added myemail+eufy@gmail.com to indicate to me this was tied to my eufy account and if eufy ever started to spam me I can just block myemail+eufy. You can use a + anything@gmail as a way to filter emails.

**Comment by imperatorviken** [comment]
oh ok thx
